#!/bin/bash

DOCKER_REGISTRY=""
IMAGE_NAME=""
FROM_TAG=""
TO_TAG=""

docker tag $DOCKER_REGISTRY/$IMAGE_NAME:$FROM_TAG $DOCKER_REGISTRY/$IMAGE_NAME:$TO_TAG
docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TO_TAG
